# Generated by Django 5.2.15 on 2026-07-08 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=300)),
                ('college', models.CharField(blank=True, max_length=50)),
                ('branch', models.CharField(blank=True, max_length=20)),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('looking_for', models.CharField(blank=True, choices=[('PROJECT', 'Project Collaborator'), ('HACKATHON', 'Hackathon Team'), ('STUDY', 'Study Buddy'), ('OPENSOURCE', 'Open Source'), ('RESEARCH', 'Research')], default='PROJECT', max_length=30)),
                ('availability', models.CharField(blank=True, choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('NOTLOOKING', 'Not Looking')], default='AVAILABLE', max_length=30)),
                ('github_url', models.URLField(blank=True, max_length=100)),
                ('linkedin_url', models.URLField(blank=True, max_length=100)),
                ('portfolio_url', models.URLField(blank=True, max_length=100)),
                ('email_visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PRIVATE', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
