# Generated by Django 5.2.15 on 2026-07-27 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_project_members_alter_project_owner_joinrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_visibility',
        ),
    ]
